---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - name: Restart server
      command: /sbin/shutdown -r 1
      async: 0
      poll: 0
    - name: Wait for server to reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=10 timeout=300
      become: false
    - wait_for:
        host: 0.0.0.0
        port: 3306
        state: stopped
        timeout: 10
    - command: "mysql -u root"
      ignore_errors: yes
      register: isrootpass_req
      failed_when: "'Access denied' not in isrootpass_req.stderr"
    - name: Check if can login w/ redhat pass
      command: "mysql -u root --password=redhat"
    - debug:
        msg: "You Passed!!!!"
