---
- hosts: host2
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - name: Start Firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: Install Samba
      yum: pkg={{item}} state=installed
      with_items:
       - samba
       - samba-client
       - policycoreutils-python
    - name: Create group marketing
      group:
        name: marketing
        state: present
    - name: Create /smbshare dir
      file:
        path: /smbshare
        state: directory
        group: marketing
    #    mode: 2775 --> this was not working
    - name: chmod 2775 /smbshare
      shell: chmod 2775 /smbshare
    - name: Add samba_share_t to /smbshare
      shell: semanage fcontext -a -t samba_share_t '/smbshare(/.*)?'
    - name: Restore the context
      shell: restorecon -vvFR /smbshare
    - name: Change workgroup in smb.conf to SAMBA
      lineinfile:
        dest: /etc/samba/smb.conf
        regexp: '\tworkgroup = SAMBA'
        line: '        workgroup = mycompany'
    - name: Add share config to smb.conf
      lineinfile:
        dest: /etc/samba/smb.conf
        line: '[smbshare]'
    # Not sure how to do tabs w/ lineinfile and samba requires it
    - shell: echo -e '\tpath= /smbshare' >>/etc/samba/smb.conf
    - shell: echo -e '\twrite list = @marketing' >>/etc/samba/smb.conf
    - shell: echo -e '\tread list = rob' >>/etc/samba/smb.conf
    - name: Create user brian in grp marketing
      user:
        name: brian
        shell: /sbin/nologin
        groups: marketing
        state: present
    - name: Set smbpasswd for Brian
      shell: '(echo "redhat"; echo "redhat") | smbpasswd -s -a brian'
    - name: Create user rob
      user:
        name: rob
        shell: /sbin/nologin
        state: present
    - name: Set smbpasswd for Rob
      shell: '(echo "redhat"; echo "redhat") | smbpasswd -s -a rob'
    - name: Start smb service
      service:
        name: smb
        state: started
        enabled: yes
    - name: Start samba browing svc (nmb)
      service:
        name: nmb
        state: started
        enabled: yes
    - name: Add samba to the fw
      command: firewall-cmd --permanent --add-service=samba
    - name: Reload fw
      command: firewall-cmd --reload

# View samba shares:   smbclient -L localhost -U rob 
# View samba users:    pbedit -L
# View selinux alerts: sealert -a /var/log/audit/audit.log
