---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - name: Restart server
      command: /sbin/shutdown -r 1
      async: 0
      poll: 0
    - name: Wait for server to reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=15 timeout=300
      become: false
    - name: root, check select privs to inventory
      shell: "mysql -u root -e 'use inventory; SELECT * FROM inventory'" 
    - name: root, check insert privs to inventory
      shell: mysql -u root -e "use inventory; INSERT into inventory (Name) VALUES ('Racks');" 
    - name: root, check update privs to inventory
      shell: mysql -u root -e "use inventory; UPDATE inventory SET Name='MyBrand_of_Racks' where id=4;" 
    - name: root, check delete privs to inventory
      shell: mysql -u root -e "use inventory; DELETE FROM inventory WHERE Name LIKE 'MyBrand_of_Racks';" 
    - debug:
        msg: "You Passed!!!!"
