---
- hosts: all
  pre_tasks:
    - assert:
        that:
          - ansible_version.major == 2
  become: yes
  become_method: sudo
  tasks:
   - name: 

          Note2: You can see this message in /etc/motd
