# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 2048
    v.cpus = 4
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "setup.yaml"
  end
end
