---
- hosts: all
  pre_tasks:
    - assert:
        that:
          - ansible_version.major == 2
  become: yes
  become_method: sudo
  tasks:
   - name: Restart Server
     shell: reboot
     async: 1
     poll: 0
   - name: Wait for server to reboot
     local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30 timeout=300
     become: false
