---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - name: Restart server
      command: /sbin/shutdown -r 1
      async: 0
      poll: 0
    - name: Wait for server to reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=15 timeout=300 port={{ ansible_ssh_port }}
      become: false
    - name: Check httpd service is active and on
      service:
        name: httpd
        state: started
        enabled: yes
      register: ischanged
    - name: Fail if httpd is not set right
      fail:
        msg: "Failed to set httpd service correctly"
      when: ischanged.changed
    - debug:
        msg: "You Passed!!!!"
