---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Disable httpd
      service:
        name: httpd
        enabled: no
