---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
    - find: path=/etc/yum.repos.d
      register: myfiles
    - file:
        state: absent
        path: "{{ item.path }}"
      with_items: "{{ myfiles.files }}"
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Disable httpd
      service:
        name: httpd
        enabled: no
    - name: Set Practice Tasks
      blockinfile:
        dest: /etc/motd
        block: |
          1. Turn httpd service on
          2. Make the service persistent
          Note: You can find rpms here: http://mirror.centos.org/centos/7/os/x86_64
          Note2: You can see this message in /etc/motd
