---
- hosts: host2
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    ### Setup sendmail as SMTP/MSA server
    - yum: name=sendmail state=present
    - lineinfile:
        dest: 
        regexp: 
        line: 
    - service:
        name: 
        state: 
        enabled: 
    - service:
        name: firewalld
        state: started
        enabled: yes

