---
- hosts: host1
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - service:
        name: firewalld
        state: started
        enabled: yes
    - yum: state=present name={{ item }}
      with_items:
        - krb5-workstation
        - pam_krb5
        - wget
    - name: Edit ssh_config for GSS authentication
      lineinfile:
        dest: /etc/ssh/ssh_config
        regexp: '#   GSSAPIAuthentication no'
        line: '    GSSAPIAuthentication yes'
    - name: Edit ssh_config for GSS delegate creds
      lineinfile:
        dest: /etc/ssh/ssh_config
        regexp: '#   GSSAPIDelegateCredentials no'
        line: '    GSSAPIDelegateCredentials yes'
    - service:
        name: sshd
        state: restarted
    - lineinfile:
        dest: /etc/krb5.conf
        line: "# Configuration snippets may be placed in this directory as well"
        state: absent
    - name: Uncomment all lines in /etc/krb5.conf
      command: "sed -i 's/#//g' /etc/krb5.conf"
    - lineinfile:
        dest: /etc/krb5.conf
        regexp: "  kdc = kerberos.example.com"
        line: "  kdc = host2.example.com"
    - lineinfile:
        dest: /etc/krb5.conf
        regexp: "  admin_server = kerberos.example.com"
        line: "  admin_server = host2.example.com"
    - name: Enable PAM for kerberos
      shell: authconfig --enablekrb5 --update
    - name: Create user01
      user:
        name: user01
        state: present
    - name: Set user01 pass to user01
      command: "echo 'user01' | passwd user01 --stdin"
    - name: Create user02 
      user:
        name: user02
        state: present
    - name: Set user02 pass to user02
      command: "echo 'user02' | passwd user02 --stdin"
    - find: path=/etc/yum.repos.d
      register: myfiles
    - file: 
        state: absent 
        path: "{{ item.path }}"
      with_items: "{{ myfiles.files }}"
    - command: "sed -i 's/127.0.0.1.*host1.*host1/192.168.6.6 host1.example.com host1/g' /etc/hosts"
    - lineinfile:
        dest: /etc/hosts
        line: "192.168.6.66 host2.example.com host2"
    - name: Set Practice Tasks
      blockinfile:
        dest: /etc/motd
        block: |
          Setup host1 to exort nfs share
          WARNING - as of this writing RHCE is on 7.0, this practice is on 7.2 and will vary ~5%
          PRE-REQ:
          1. Your krb5.keytab is here http://192.168.6.66/krb5.keytab
          TASKS:
          1. Setup an NFS share called /securenfs
          2. Securely export nfs share with selinux contexts
          3. Enable r/w for user01
          OPTIONAL: (ungraded)
          1. Open up remote showmount access (mountd, rpc-bind)
          Note: You can find rpms here: http://mirror.centos.org/centos/7/os/x86_64
          Note2: You can see this message in /etc/motd
