---
- hosts: host1
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
    - yum:
        name: mod_ssl
        state: present
    - service:
        name: httpd 
        state: started
        enabled: yes
    - find: path=/etc/yum.repos.d
      register: myfiles
    - file: 
        state: absent 
        path: "{{ item.path }}"
      with_items: "{{ myfiles.files }}"
    - file:
        state: touch
        path: /var/www/html/index.html
    - lineinfile:
        dest: /var/www/html/index.html
        line: "COFFEE!!!!!!!!!"
    - service:
        name: firewalld
        state: started
        enabled: yes
    - name: Set Practice Tasks
      blockinfile:
        dest: /etc/motd
        block: |
          1. Firewalld config on host1 must use the dmz zone for all unspecified cons and 192.168.7.0/24
          2. Traffic from 192.168.6.0/24 must be routed to the work zone
          3. The work zone should have all necessary ports for https opened, but unencrypted http traffic should be filtered 
          Note: You can find rpms here: http://mirror.centos.org/centos/7/os/x86_64
          Note2: You can see this message in /etc/motd
