---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    # Note: do not want to reboot or you will solve prob for user as dhcp grabs new resolv.conf details
    - name: "Test host1 resolv google.com"
      command: dig @192.168.6.6 A google.com
    - debug:
        msg: "You Passed!!!!"
