---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - name: Restart server
      command: /sbin/shutdown -r 1
      async: 0
      poll: 0
    - name: Wait for server to reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=15 timeout=300 port={{ ansible_ssh_port }}
      become: false
    - name: "Test dns access to host1 (eth1: 192.168.6.6)"
      command: dig @192.168.6.6 A google.com
      when: ansible_hostname == "host1"
    - debug:
        msg: "You Passed!!!!"
