---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    # Note: not rebooting here b/c it is users job to fix and test what needs to be so the svc is up
    - name: "Test dns access to host1 (eth1: 192.168.6.6)"
      command: dig @192.168.6.6 A google.com
      when: ansible_hostname == "host1"
    - debug:
        msg: "You Passed!!!!"
