---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - name: Restart server
      command: /sbin/shutdown -r 1
      async: 0
      poll: 0
    - name: Wait for server to reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=15 timeout=300
      become: false
    - name: Fail if ipv6 addr is wrong on host1
      fail:
        msg: "eth1 ipv6 addr == {{ ansible_eth1.ipv6[0].address }}, wanted fddb:fe2a:ab1e::c0a8:3"
      when: ansible_hostname == "host1" and ansible_eth1.ipv6[0].address != "fddb:fe2a:ab1e::c0a8:3"
    - name: Test ping6 from host1 to host2 on ipv6 int
      command: ping6 -I eth1 -c 3 "fddb:fe2a:ab1e::c0a8:2"
      when: ansible_hostname == "host1"
    - debug:
        msg: "You Passed!!!!"
