# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.define "host1" do |host1|
    host1.vm.network :private_network, ip: "fddb:fe2a:ab1e::c0a8:1"
    host1.vm.hostname = 'host1'
    host1.vm.provider :virtualbox do |v|
      v.memory = 1024
      v.cpus = 4
    end
  end

  config.vm.define "host2" do |host2|
    host2.vm.network :private_network, ip: "fddb:fe2a:ab1e::c0a8:2"
    host2.vm.hostname = 'host2'
    host2.vm.provider :virtualbox do |v|
      v.memory = 1024
      v.cpus = 4
    end
    # Workaround for eth1 not starting on boot
    host2.vm.provision "shell" do |s|
      s.inline = "ifup eth1"
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "setup.yaml"
  end
end
