---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
    - name: Restart server
      command: /sbin/shutdown -r -t sec 15
      async: 0
      poll: 0
    - name: Wait for server to reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=10 timeout=300
      become: false
    - name: Fail if ipv4 addr is wrong on team0 on host1
      fail:
        msg: "team0 ipv4 addr == {{ ansible_team0.ipv4.address }}, wanted 192.168.7.8"
      when: ansible_team0.ipv4.address != "192.168.7.8"
    - name: Check runner type of team0
      command: bash -c "teamdctl team0 state | grep activebackup | awk '{print $2}'"
      register: runnertype
    - name: Fail if runner type is not activebackup
      fail: 
        msg: "The runner for team0 is {{ runnertype.stdout }}, wanted activebackup"
      when: runnertype.stdout != "activebackup"
    - debug:
        msg: "You Passed!!!!"
