---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
    - name: Remove repo file
      file:
        path: "/etc/yum.repos.d/*.repo"
        state: absent
    - name: Manage eth1 
      command: sed -i 's/NM_CONTROLLED=no/NM_CONTROLLED=yes/' /etc/sysconfig/network-scripts/ifcfg-eth1
    - name: Manage eth2
      command: sed -i 's/NM_CONTROLLED=no/NM_CONTROLLED=yes/' /etc/sysconfig/network-scripts/ifcfg-eth2
    - name: Reload config
      command: nmcli con reload
    - name: Create team0 profile
      # Normally appended to end of cli like so: config '{"runner": {"name": "activebackup"}}'
      # Defaults to roundrobin
      command: nmcli con add type team con-name team0 ifname team0 
    - name: Create port from eth1
      command: nmcli con add type team-slave ifname eth1 master team0
    - name: Create port from eth2
      command: nmcli con add type team-slave ifname eth2 master team0
    - name: Set team0 ipaddr and method
      command: nmcli con mod team0 ipv4.addresses 192.168.7.8/24 ipv4.method manual
    - name: Bring up eth1 slave, which will bring up master
      command: nmcli con up team-slave-eth1
    - name: Bring up eth2 slave
      command: nmcli con up team-slave-eth2
    - name: Set Practice Tasks
      blockinfile:
        dest: /etc/motd
        block: |
          1. Change the runner for team0 to activebackup from roundrobin on host1
          2. Check success by pinging 192.168.7.9 (host2) from the team int (can use ping -I). Make sure to check host2 eth1 is up JIC. 
          Note: You can find rpms here: http://mirror.centos.org/centos/7/os/x86_64
          Note2: You can see this message in /etc/motd
