---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
    - name: Restart server
      command: /sbin/shutdown -r -t sec 15
      async: 0
      poll: 0
    - name: Wait for server to reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=10 timeout=300
      become: false
    - name: Check for default target
      # to see targets: systemctl list-units --type=target --all
      command: systemctl get-default 
      register: default_target
    - name: Fail if default target is wrong
      fail:
        msg: "default target == {{ default_target.stdout }}, wanted graphical.target"
      when: default_target.stdout != "graphical.target"
    - debug:
        msg: "You Passed!!!!"
