---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - name: Restart server
      command: /sbin/shutdown -r 1
      async: 0
      poll: 0
    - name: Wait for server to reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started delay=15 timeout=300 port={{ ansible_ssh_port }}
      become: false
    - name: Fail if ipv4 addr is wrong
      fail:
        msg: "eth1 ipv4 addr == {{ ansible_eth1.ipv4.address }}, wanted 192.168.7.66"
      when: ansible_eth1.ipv4.address != "192.168.7.66"
    - name: Test ping from host1 to host2 on eth1 int
      command: ping -c 3 -I eth1 "192.168.7.7"
    - debug:
        msg: "You Passed!!!!"
