---
- hosts: host2
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - service:
        name: firewalld
        state: started
        enabled: yes
    - yum:
        name: '{{ item }}'
        state: present
      with_items:
        - '@mariadb-client'
        - MySQL-python
