---
- hosts: host1
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
        enabled: yes
    - service:
        name: firewalld
        state: started
        enabled: yes
    - yum:
        name: '{{ item }}'
        state: present
      with_items:
        - '@mariadb'
        - '@mariadb-client'
        - MySQL-python
    - service:
        name: mariadb
        state: started
    - name: Create a new database with name inventory
      mysql_db:
        name: inventory
        state: present
    - shell: "echo 'use inventory; CREATE TABLE inventory (ID int NOT NULL AUTO_INCREMENT, Name varchar(255) NOT NULL, PRIMARY KEY (id));' | mysql -u root"
    - shell: echo "use inventory; INSERT into inventory (Name) VALUES ('Networking'), ('Servers'), ('Ssd');" | mysql -u root
    - find: path=/etc/yum.repos.d
      register: myfiles
    - file: 
        state: absent 
        path: "{{ item.path }}"
      with_items: "{{ myfiles.files }}"
    - name: Set Practice Tasks
      blockinfile:
        dest: /etc/motd
        block: |
          1. Create users john (pass=john_password) and steve (steve_password)
          2. john can connect only from localhost and steve from any host
          2. Grant insert, update, delete, and select privs on inventory db to user john
          3. Grant select privs on inventory db to Steve
          4. Test it
          Note: You can find rpms here: http://mirror.centos.org/centos/7/os/x86_64
          Note2: You can see this message in /etc/motd
