---
- hosts: host1
  become: yes
  become_method: sudo
  tasks:
    - name: Check for ansible v2
      assert:
        that:
          - ansible_version.major == 2
    - yum:
        name: httpd
        state: present
    - service:
        name: httpd 
        state: started
        enabled: yes
    - find: path=/etc/yum.repos.d
      register: myfiles
    - file: 
        state: absent 
        path: "{{ item.path }}"
      with_items: "{{ myfiles.files }}"
    - file:
        state: touch
        path: /var/www/html/index.html
    - lineinfile:
        dest: /var/www/html/index.html
        line: "Awesome broh!"
    - service:
        name: firewalld
        state: started
        enabled: yes
    - name: Set Practice Tasks
      blockinfile:
        dest: /etc/motd
        block: |
          1. Get httpd to start on port 82 (a non-standard port)
          2. Set a firewalld rule to open port 82 to httpd
          3. Check for success by using curl from host2 to httpd svc on host1
          Note: You can find rpms here: http://mirror.centos.org/centos/7/os/x86_64
          Note2: You can see this message in /etc/motd
